# Generated by Django 4.0 on 2021-12-23 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='faculty',
            unique_together={('id_no', 'name')},
        ),
    ]
